Fix instance not defined error
Added a test for the generate function revealed an error:

```javascript
ReferenceError: instance is not defined

      at Object.generate (app.js:9:14)
```

This appears to be caused by an accidental global.