Filter newlines out of phrase list
The generatePhrases function was checking for '' and ' ' but not '\n'.
Input text containing new lines would find their way into the phrase
list and then blow up in calculateKeywordScores when word_list.length
was called. The error was:

```javascript
TypeError: Cannot read property 'length' of null
```